//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.Ratings = new HashSet<Rating>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int Id { get; set; }
        public int MenuSectionId { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual MenuSection MenuSection { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
    }
}
