//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSection
    {
        public MenuSection()
        {
            this.FoodItems = new HashSet<FoodItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DessertId { get; set; }
        public Nullable<int> DrinkId { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> SoupSaladId { get; set; }
        public Nullable<int> AppetizerId { get; set; }
        public Nullable<int> OtherId { get; set; }
        public Nullable<int> EntreeId { get; set; }
        public int Entity1Id { get; set; }
        public Nullable<int> SpecialId { get; set; }
        public Nullable<int> BreakfastId { get; set; }
        public Nullable<int> SideId { get; set; }
        public Nullable<int> SauceId { get; set; }
    
        public virtual ICollection<FoodItem> FoodItems { get; set; }
        public virtual Dessert Dessert { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual SoupSalad SoupSalad { get; set; }
        public virtual Appetizer Appetizer { get; set; }
        public virtual Other Other { get; set; }
        public virtual Entree Entree { get; set; }
        public virtual Special Special { get; set; }
        public virtual Breakfast Breakfast { get; set; }
        public virtual Side Side { get; set; }
        public virtual Sauce Sauce { get; set; }
    }
}
