//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Appetizer> Appetizers { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<MenuSection> MenuSections { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Entree> Entrees { get; set; }
        public virtual DbSet<SoupSalad> SoupSalads { get; set; }
        public virtual DbSet<Other> Other { get; set; }
        public virtual DbSet<Drink> Drinks { get; set; }
        public virtual DbSet<Dessert> Desserts { get; set; }
        public virtual DbSet<Side> Sides { get; set; }
        public virtual DbSet<Breakfast> Breakfasts { get; set; }
        public virtual DbSet<Sauce> Sauces { get; set; }
        public virtual DbSet<Special> Specials { get; set; }
        public virtual DbSet<ProfileImage> ProfileImages { get; set; }
    }
}
