//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StreetAddress { get; set; }
        public string LocuId { get; set; }
        public string WebsiteURL { get; set; }
        public string Phone { get; set; }
        public string lon { get; set; }
        public string lat { get; set; }
        public string region { get; set; }
        public string zip { get; set; }
        public string googleId { get; set; }
    
        public virtual Dessert Dessert { get; set; }
        public virtual Other Other { get; set; }
        public virtual SoupSalad SoupSalad { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Entree Entree { get; set; }
        public virtual Appetizer Appetizer { get; set; }
    }
}
